export const businessTypesList = [
    { value: 'CARTÓRIO', label: 'CARTÓRIO', id: 1 },
    { value: 'CASA DE SHOWS', label: 'CASA DE SHOWS', id: 2 },
    { value: 'CLÍNICA', label: 'CLÍNICA', id: 3 },
    { value: 'COMERCIAL', label: 'COMERCIAL', id: 4 },
    { value: 'CONCRETEIRA', label: 'CONCRETEIRA', id: 5 },
    { value: 'CONDOMÍNIO COMERCIAL', label: 'CONDOMÍNIO COMERCIAL', id: 6 },
    { value: 'CONDOMÍNIO RESIDÊNCIAL', label: 'CONDOMÍNIO RESIDÊNCIAL', id: 7 },
    { value: 'CONSTRUTORA', label: 'CONSTRUTORA', id: 8 },
    { value: 'ESPAÇO PÚBLICO', label: 'ESPAÇO PÚBLICO', id: 9 },
    { value: 'ESTÁDIO', label: 'ESTÁDIO', id: 10 },
    { value: 'GINÁSIO DE ESPORTES', label: 'GINÁSIO DE ESPORTES', id: 11 },
    { value: 'HOSPITAL', label: 'HOSPITAL', id: 12 },
    { value: 'HOTEL', label: 'HOTEL', id: 13 },
    { value: 'INDÚSTRIA', label: 'INDÚSTRIA', id: 14 },
    { value: 'INSTITUIÇÃO BANCÁRIA', label: 'INSTITUIÇÃO BANCÁRIA', id: 15 },
    { value: 'INSTITUIÇÃO DE ENSINO', label: 'INSTITUIÇÃO DE ENSINO', id: 16 },
    { value: 'LOTEAMENTO', label: 'LOTEAMENTO', id: 17 },
    { value: 'MINERADORA', label: 'MINERADORA', id: 18 },
    { value: 'MOTEL', label: 'MOTEL', id: 19 },
    { value: 'MUSEU', label: 'MUSEU', id: 20 },
    { value: 'ORGÃO PÚBLICO', label: 'ORGÃO PÚBLICO', id: 21 },
    { value: 'OUTROS / NÃO INFORMADO', label: 'OUTROS / NÃO INFORMADO', id: 22 },
    { value: 'PARQUE', label: 'PARQUE', id: 23 },
    { value: 'PONTE', label: 'PONTE', id: 24 },
    { value: 'PORTO', label: 'PARQUE', id: 25 },
    { value: 'POSTO DE COMBUSTÍVEL', label: 'POSTO DE COMBUSTÍVEL', id: 26 },
    { value: 'PRAÇA', label: 'PRAÇA', id: 27 },
    { value: 'REFLORESTADORA', label: 'REFLORESTADORA', id: 28 },
    { value: 'RESIDÊNCIA UNIFAMILIAR', label: 'RESIDÊNCIA UNIFAMILIAR', id: 29 },
    {
      value: 'RESIDENCIAL E COMERCIAL (MISTO)',
      label: 'RESIDENCIAL E COMERCIAL (MISTO)',
      id: 30,
    },
    { value: 'RURAL', label: 'RURAL', id: 31 },
    { value: 'SHOPPING CENTER', label: 'SHOPPING CENTER', id: 32 },
    { value: 'SUPERMERCADO', label: 'SUPERMERCADO', id: 33 },
    {
      value: 'TEMPLO RELIGIOSO / IGREJA',
      label: 'TEMPLO RELIGIOSO / IGREJA',
      id: 34,
    },
    { value: 'VIADUTO', label: 'VIADUTO', id: 35 },
  ];